# Generated by Django 2.2.7 on 2021-08-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='car_thumbnails')),
                ('cover', models.ImageField(upload_to='car_covers')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('First Class', 'First Class'), ('Executive', 'Executive'), ('Business', 'Business'), ('XL', 'XL')], max_length=40)),
                ('quality_one', models.CharField(blank=True, default='Passenger: 4', max_length=100)),
                ('quality_two', models.CharField(blank=True, default='Luggages: 2', max_length=100)),
                ('decription', models.TextField()),
                ('hourly_rate', models.IntegerField(blank=True, default=50, null=True)),
                ('daily_rate', models.IntegerField(blank=True, default=350, null=True)),
                ('slug', models.SlugField(default='please-input-in-this-format', max_length=100)),
            ],
        ),
    ]
