# Generated by Django 2.2.7 on 2021-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='daily_rate',
            field=models.IntegerField(default=350),
        ),
        migrations.AlterField(
            model_name='car',
            name='hourly_rate',
            field=models.IntegerField(default=50),
        ),
    ]
