# Generated by Django 2.2.7 on 2021-08-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'db_table': 'testimonials',
            },
        ),
    ]
